name: Mona's pipeline

on:
  push:
    branches:
      - mona/*

env:
  DEV: mona-dev
  TEST: mona-test
  PROD: mona-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build all the code
        run: echo "building application package"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: app-artifacts
          path: .
          retention-days: 1 # optional


  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [${{ env.DEV }}, ${{ env.TEST }}]
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: build

      - name: Deploy to ${{ matrix.environment }}
        run: echo "Deploying to ${{ matrix.environment }}"

      - name: Running Test on ${{ matrix.environment }}
        run: echo "Execute test on ${{ matrix.environment }}"

  prod:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: [${{ env.PROD }}]
    steps:
      - name: Download build artifacts
        run: echo "Download to ${{ environment }}"

      - name: Deploy to ${{ environment }}
        run: echo "Deploying to ${{ environment }}"

      - name: Smoke Test on ${{ environment }}
        run: echo "Smoking ${{ environment }}"
