name: Mona's pipeline
run-name: ${{ github.actor }} testing actions

on:
  push:
    branches:
      - mona/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build all the code
        run: echo "building application package"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: app-artifacts
          path: .
          retention-days: 1 # optional

  dev:
    needs: build
    strategy:
      matrix:
        environment: [ mona-dev, mona-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-artifacts
          path: build

      - name: Deploy to ${{ matrix.environment }}
        run: echo "Deploying to ${{ matrix.environment }}"

      - name: Running Test on ${{ matrix.environment }}
        run: echo "Execute test on ${{ matrix.environment }}"

  perf:
    needs: build
    runs-on: ubuntu-latest
    environment: mona-perf
    steps:
      - name: Performance Test
        run: echo "Executing test"
      - name: Retrieve environment secret
        run: echo "The secret value is ${{ secrets.USERPASS }}"
        

  prod:
    needs: [ dev, perf ]
    runs-on: ubuntu-latest
    environment: mona-prod
    steps:
      - name: Retrieve environment secret
        run: echo "The secret value is ${{ secrets.USERPASS }}"

      - name: Download build artifacts
        run: echo "Download artifacts"

      - name: Deploy to prod
        run: echo "Deploying to "

      - name: Smoke Test on prod
        run: echo "Smoking prod"
